# Generated by Django 4.0 on 2022-01-20 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=50)),
                ('office_address', models.CharField(max_length=500)),
                ('office_location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('calendar_id', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('upload', models.ImageField(upload_to='covers/%Y/%m/%d/')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zanbilCalendarManager.office')),
            ],
        ),
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair_name', models.CharField(max_length=50)),
                ('calendar_id', models.CharField(max_length=100)),
                ('upload', models.ImageField(upload_to='covers/%Y/%m/%d/')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zanbilCalendarManager.office')),
            ],
        ),
    ]
