# Generated by Django 4.0 on 2022-01-20 01:44

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('zanbilCalendarManager', '0002_alter_chair_chair_name_alter_office_office_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='office_location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
