# Generated by Django 4.0 on 2022-01-23 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zanbilCalendarManager', '0003_alter_office_office_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chair',
            old_name='chair_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='office_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='office_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='office_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_name',
            new_name='name',
        ),
    ]
