# Generated by Django 4.0 on 2022-01-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zanbilCalendarManager', '0004_rename_chair_name_chair_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chair',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='office',
            name='location',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%d/'),
        ),
    ]
