# Generated by Django 4.0 on 2022-01-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zanbilCalendarManager', '0006_space_delete_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='type',
            field=models.CharField(choices=[('c', 'Chair'), ('r', 'Room')], default='c', max_length=1),
        ),
    ]
