# Generated by Django 4.0 on 2022-01-24 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zanbilCalendarManager', '0008_alter_space_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chair',
        ),
    ]
