# Generated by Django 4.0 on 2022-01-28 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zanbilCalendarManager', '0009_delete_chair'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='upload',
            new_name='image',
        ),
    ]
