# Generated by Django 4.0 on 2022-02-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zanbilCalendarManager', '0012_rename_user_spacestraffic_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=100, verbose_name='summary')),
                ('start', models.DateTimeField(verbose_name='Start date & time')),
                ('end', models.DateTimeField(verbose_name='End date & time')),
                ('attendees', models.ManyToManyField(to='zanbilCalendarManager.Attendee')),
            ],
        ),
    ]
