# Generated by Django 4.0 on 2022-03-06 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zanbilCalendarManager', '0016_accessibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zanbilCalendarManager.space'),
        ),
    ]
