# Generated by Django 4.0 on 2022-03-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zanbilCalendarManager', '0017_event_space'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Space',
            new_name='space',
        ),
    ]
