# Generated by Django 4.0 on 2022-03-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zanbilCalendarManager', '0018_rename_space_event_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='googleId',
            field=models.CharField(max_length=500, null=True, verbose_name='Google Calendar ID'),
        ),
    ]
