# Generated by Django 4.0 on 2022-03-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zanbilCalendarManager', '0019_event_googleid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='googleId',
            new_name='google_id',
        ),
    ]
