# Generated by Django 4.0 on 2022-03-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zanbilCalendarManager', '0020_rename_googleid_event_google_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('b', 'Busy'), ('d', 'Deleted')], default='p', max_length=1),
        ),
    ]
