# Generated by Django 4.0 on 2022-04-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zanbilCalendarManager', '0023_space_calendar_embed_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='calendar_embed_link',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Google calendar embed link'),
        ),
    ]
