# Generated by Django 4.0 on 2022-05-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zanbilCalendarManager', '0028_remove_spacestraffic_event_gid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('status', models.CharField(choices=[('p', 'Pending'), ('r', 'Resolved')], default='p', max_length=1)),
            ],
        ),
    ]
