# Generated by Django 4.0 on 2022-05-30 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zanbilCalendarManager', '0029_contactusmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusmessages',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Request Time'),
            preserve_default=False,
        ),
    ]
