# Generated by Django 4.0 on 2022-05-30 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zanbilCalendarManager', '0030_contactusmessages_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUsMessages',
            new_name='ContactUsMessage',
        ),
    ]
