# Generated by Django 4.0 on 2022-06-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zanbilCalendarManager', '0031_rename_contactusmessages_contactusmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrent',
            field=models.BooleanField(default=False, verbose_name='Recurrent Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='sequence_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sequence Number'),
        ),
    ]
