# Generated by Django 4.0 on 2022-06-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zanbilCalendarManager', '0032_event_recurrent_event_sequence_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrent_period',
            field=models.CharField(blank=True, choices=[('d', 'Day'), ('w', 'Week'), ('m', 'Month')], max_length=1, null=True),
        ),
    ]
